364-intial-agent-documentation
trustgrid/docs pull request #417
Opened 2024-02-13 15:41 UTC by Deadtired78

2024-02-14 00:36 UTC, terrbear commented on content/en/tutorials/agent-deploy/index.md
> +The below instructions for Red Hat Enterprise Linux (RHEL) may also work for related distributions,  like Fedora and CentOS, but this has not been validated by Trustgrid.
missing rhel instructions

2024-02-14 20:22 UTC, Deadtired78 commented on content/en/tutorials/agent-deploy/index.md
> +The below instructions for Red Hat Enterprise Linux (RHEL) may also work for related distributions,  like Fedora and CentOS, but this has not been validated by Trustgrid.
removed

2024-02-14 20:30 UTC, terrbear approved these changes

2024-02-19 21:07 UTC, terrbear requested changes

2024-02-19 21:07 UTC, terrbear commented on content/en/docs/nodes/appliances/vrfs/index.md
> +Using the example below if a source packet is initiated from within 10.10.10.0/24 destined for anything in 192.168.10.0/24 the source would be translated to the interface address the packet is eGREss
Find/replace capitalization again :)

2024-02-20 19:21 UTC, terrbear approved these changes

2024-02-22 20:30 UTC, merged