C-5.22.0 Release Notes
trustgrid/docs pull request #439
Opened 2024-03-20 19:00 UTC by Deadtired78

2024-03-20 19:12 UTC, terrbear requested changes

2024-03-20 19:12 UTC, terrbear commented on content/en/docs/user-management/groups/index.md
> +These groups are created in the portal via the `Add Group` button. Membership is managed directly within the portal by administrators.
s/portal/Portal

2024-03-20 19:12 UTC, terrbear commented on content/en/docs/user-management/groups/index.md
> +### Trustgrid-native Groups
capitalization diff b/w this line and the one below post-hyphen

2024-03-20 19:12 UTC, terrbear commented on content/en/docs/user-management/groups/index.md
> +These groups are create based on Identity Provider (IdP) configuration for select IdPs (currently Gsuite and Azure OpenID). The IdP can be configured to sync all or select groups, and the sync proces
`G Suite`

2024-03-21 18:51 UTC, trustgridjack approved these changes

2024-03-21 18:56 UTC, terrbear approved these changes

2024-03-21 18:57 UTC, merged